# coding=utf-8
#####################################################
# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT #
#####################################################
# noqa: E128,E201
from .client import BaseClient
from .client import createApiClient
from .client import config
from .client import createTemporaryCredentials
from .client import createSession
_defaultConfig = config


class Github(BaseClient):
    """
    The github service, typically available at
    `github.taskcluster.net`, is responsible for publishing pulse
    messages in response to GitHub events.

    This document describes the API end-point for consuming GitHub
    web hooks
    """

    classOptions = {
        "baseUrl": "https://github.taskcluster.net/v1"
    }

    def githubWebHookConsumer(self, *args, **kwargs):
        """
        Consume GitHub WebHook

        Capture a GitHub event and publish it via pulse, if it's a push,
        release or pull request.

        This method is ``experimental``
        """

        return self._makeApiCall(self.funcinfo["githubWebHookConsumer"], *args, **kwargs)

    def builds(self, *args, **kwargs):
        """
        List of Builds

        A paginated list of builds that have been run in
        Taskcluster. Can be filtered on various git-specific
        fields.

        This method takes output: ``http://schemas.taskcluster.net/github/v1/build-list.json#``

        This method is ``experimental``
        """

        return self._makeApiCall(self.funcinfo["builds"], *args, **kwargs)

    def ping(self, *args, **kwargs):
        """
        Ping Server

        Respond without doing anything.
        This endpoint is used to check that the service is up.

        This method is ``stable``
        """

        return self._makeApiCall(self.funcinfo["ping"], *args, **kwargs)

    funcinfo = {
        "githubWebHookConsumer": {           'args': [],
            'method': u'post',
            'name': u'githubWebHookConsumer',
            'route': u'/github',
            'stability': u'experimental'},
        "ping": {           'args': [],
            'method': u'get',
            'name': u'ping',
            'route': u'/ping',
            'stability': u'stable'},
        "builds": {           'args': [],
            'method': u'get',
            'name': u'builds',
            'output': u'http://schemas.taskcluster.net/github/v1/build-list.json#',
            'query': [           u'continuationToken',
                                 u'limit',
                                 u'organization',
                                 u'repository',
                                 u'sha'],
            'route': u'/builds',
            'stability': u'experimental'},
    }


__all__ = ['createTemporaryCredentials', 'config', '_defaultConfig', 'createApiClient', 'createSession', u'Github']
